#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CanvasDemo.Resource", IsApplication=true)]

namespace CanvasDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Controls.Resource.Attribute.captionText = global::CanvasDemo.Resource.Attribute.captionText;
			global::Xamarin.Controls.Resource.Attribute.captionTextColor = global::CanvasDemo.Resource.Attribute.captionTextColor;
			global::Xamarin.Controls.Resource.Attribute.captionTextSize = global::CanvasDemo.Resource.Attribute.captionTextSize;
			global::Xamarin.Controls.Resource.Attribute.clearLabelText = global::CanvasDemo.Resource.Attribute.clearLabelText;
			global::Xamarin.Controls.Resource.Attribute.clearLabelTextColor = global::CanvasDemo.Resource.Attribute.clearLabelTextColor;
			global::Xamarin.Controls.Resource.Attribute.clearLabelTextSize = global::CanvasDemo.Resource.Attribute.clearLabelTextSize;
			global::Xamarin.Controls.Resource.Attribute.signatureLineColor = global::CanvasDemo.Resource.Attribute.signatureLineColor;
			global::Xamarin.Controls.Resource.Attribute.signatureLineSpacing = global::CanvasDemo.Resource.Attribute.signatureLineSpacing;
			global::Xamarin.Controls.Resource.Attribute.signatureLineWidth = global::CanvasDemo.Resource.Attribute.signatureLineWidth;
			global::Xamarin.Controls.Resource.Attribute.signaturePromptText = global::CanvasDemo.Resource.Attribute.signaturePromptText;
			global::Xamarin.Controls.Resource.Attribute.signaturePromptTextColor = global::CanvasDemo.Resource.Attribute.signaturePromptTextColor;
			global::Xamarin.Controls.Resource.Attribute.signaturePromptTextSize = global::CanvasDemo.Resource.Attribute.signaturePromptTextSize;
			global::Xamarin.Controls.Resource.Attribute.strokeColor = global::CanvasDemo.Resource.Attribute.strokeColor;
			global::Xamarin.Controls.Resource.Attribute.strokeWidth = global::CanvasDemo.Resource.Attribute.strokeWidth;
			global::Xamarin.Controls.Resource.Color.signature_pad_dark_color = global::CanvasDemo.Resource.Color.signature_pad_dark_color;
			global::Xamarin.Controls.Resource.Color.signature_pad_light_color = global::CanvasDemo.Resource.Color.signature_pad_light_color;
			global::Xamarin.Controls.Resource.Dimension.signature_pad_font_size = global::CanvasDemo.Resource.Dimension.signature_pad_font_size;
			global::Xamarin.Controls.Resource.Dimension.signature_pad_line_thickness = global::CanvasDemo.Resource.Dimension.signature_pad_line_thickness;
			global::Xamarin.Controls.Resource.Dimension.signature_pad_narrow_spacing = global::CanvasDemo.Resource.Dimension.signature_pad_narrow_spacing;
			global::Xamarin.Controls.Resource.Dimension.signature_pad_wide_spacing = global::CanvasDemo.Resource.Dimension.signature_pad_wide_spacing;
			global::Xamarin.Controls.Resource.Drawable.signature_pad_background = global::CanvasDemo.Resource.Drawable.signature_pad_background;
			global::Xamarin.Controls.Resource.Id.background_image = global::CanvasDemo.Resource.Id.background_image;
			global::Xamarin.Controls.Resource.Id.caption = global::CanvasDemo.Resource.Id.caption;
			global::Xamarin.Controls.Resource.Id.clear_label = global::CanvasDemo.Resource.Id.clear_label;
			global::Xamarin.Controls.Resource.Id.signature_canvas = global::CanvasDemo.Resource.Id.signature_canvas;
			global::Xamarin.Controls.Resource.Id.signature_line = global::CanvasDemo.Resource.Id.signature_line;
			global::Xamarin.Controls.Resource.Id.signature_prompt = global::CanvasDemo.Resource.Id.signature_prompt;
			global::Xamarin.Controls.Resource.Layout.signature_pad_layout = global::CanvasDemo.Resource.Layout.signature_pad_layout;
			global::Xamarin.Controls.Resource.String.signature_pad_caption_text = global::CanvasDemo.Resource.String.signature_pad_caption_text;
			global::Xamarin.Controls.Resource.String.signature_pad_clear_label_text = global::CanvasDemo.Resource.String.signature_pad_clear_label_text;
			global::Xamarin.Controls.Resource.String.signature_pad_prompt_text = global::CanvasDemo.Resource.String.signature_pad_prompt_text;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView = global::CanvasDemo.Resource.Styleable.SignaturePadView;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_captionText = global::CanvasDemo.Resource.Styleable.SignaturePadView_captionText;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_captionTextColor = global::CanvasDemo.Resource.Styleable.SignaturePadView_captionTextColor;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_captionTextSize = global::CanvasDemo.Resource.Styleable.SignaturePadView_captionTextSize;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_clearLabelText = global::CanvasDemo.Resource.Styleable.SignaturePadView_clearLabelText;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_clearLabelTextColor = global::CanvasDemo.Resource.Styleable.SignaturePadView_clearLabelTextColor;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_clearLabelTextSize = global::CanvasDemo.Resource.Styleable.SignaturePadView_clearLabelTextSize;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_signatureLineColor = global::CanvasDemo.Resource.Styleable.SignaturePadView_signatureLineColor;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_signatureLineSpacing = global::CanvasDemo.Resource.Styleable.SignaturePadView_signatureLineSpacing;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_signatureLineWidth = global::CanvasDemo.Resource.Styleable.SignaturePadView_signatureLineWidth;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_signaturePromptText = global::CanvasDemo.Resource.Styleable.SignaturePadView_signaturePromptText;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_signaturePromptTextColor = global::CanvasDemo.Resource.Styleable.SignaturePadView_signaturePromptTextColor;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_signaturePromptTextSize = global::CanvasDemo.Resource.Styleable.SignaturePadView_signaturePromptTextSize;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_strokeColor = global::CanvasDemo.Resource.Styleable.SignaturePadView_strokeColor;
			global::Xamarin.Controls.Resource.Styleable.SignaturePadView_strokeWidth = global::CanvasDemo.Resource.Styleable.SignaturePadView_strokeWidth;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int captionText = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int captionTextColor = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int captionTextSize = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public const int clearLabelText = 2130771979;
			
			// aapt resource value: 0x7f01000d
			public const int clearLabelTextColor = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int clearLabelTextSize = 2130771980;
			
			// aapt resource value: 0x7f010002
			public const int signatureLineColor = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int signatureLineSpacing = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int signatureLineWidth = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int signaturePromptText = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int signaturePromptTextColor = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int signaturePromptTextSize = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int strokeColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int strokeWidth = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int signature_pad_dark_color = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int signature_pad_light_color = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060003
			public const int signature_pad_font_size = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int signature_pad_line_thickness = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int signature_pad_narrow_spacing = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int signature_pad_wide_spacing = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int signature_pad_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash_logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int background_image = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int btnLoad = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int btnSave = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int btnSaveImage = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int caption = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int clear_label = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int signatureView = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int signature_canvas = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int signature_line = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int signature_prompt = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int signature_pad_layout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int signature_pad_caption_text = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int signature_pad_clear_label_text = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int signature_pad_prompt_text = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SignaturePadView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 5
			public const int SignaturePadView_captionText = 5;
			
			// aapt resource value: 7
			public const int SignaturePadView_captionTextColor = 7;
			
			// aapt resource value: 6
			public const int SignaturePadView_captionTextSize = 6;
			
			// aapt resource value: 11
			public const int SignaturePadView_clearLabelText = 11;
			
			// aapt resource value: 13
			public const int SignaturePadView_clearLabelTextColor = 13;
			
			// aapt resource value: 12
			public const int SignaturePadView_clearLabelTextSize = 12;
			
			// aapt resource value: 2
			public const int SignaturePadView_signatureLineColor = 2;
			
			// aapt resource value: 4
			public const int SignaturePadView_signatureLineSpacing = 4;
			
			// aapt resource value: 3
			public const int SignaturePadView_signatureLineWidth = 3;
			
			// aapt resource value: 8
			public const int SignaturePadView_signaturePromptText = 8;
			
			// aapt resource value: 10
			public const int SignaturePadView_signaturePromptTextColor = 10;
			
			// aapt resource value: 9
			public const int SignaturePadView_signaturePromptTextSize = 9;
			
			// aapt resource value: 0
			public const int SignaturePadView_strokeColor = 0;
			
			// aapt resource value: 1
			public const int SignaturePadView_strokeWidth = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
